brew "oh-my-posh"
brew "kubernetes-cli"
brew "zsh-autosuggestions"
brew "zsh-completions"
brew "kubernetes-cli"

cask "1password"
cask "visual-studio-code"
cask "microsoft-teams"
cask "wezterm"
cask "moom"

mas "1Password for Safari", id: 1569813296

vscode "catppuccin.catppuccin-vsc"