#!/usr/bin/env bash

source "$CONFIG_DIR/colors.sh"

PLUGIN_DIR="$CONFIG_DIR/plugins"
ITEM_DIR="$CONFIG_DIR/items"

##### Bar Appearance #####
# Configuring the general appearance of the bar.
# These are only some of the options available. For all options see:
# https://felixkratz.github.io/SketchyBar/config/bar
bar=(
  height=32
  blur_radius=30
  position=top
  color=$BAR_COLOR
)
sketchybar --bar "${bar[@]}"

##### Changing Defaults #####
# We now change some default values, which are applied to all further items.
# For a full list of all available item properties see:
# https://felixkratz.github.io/SketchyBar/config/items

default=(
  padding_left=5
  padding_right=5
  icon.font="BlexMono Nerd Font:Regular:17.0"
  label.font="SF Pro:Regular:14.0"
  icon.color=$FG_COLOR
  label.color=$FG_COLOR
  icon.padding_left=4
  icon.padding_right=4
  label.padding_left=4
  label.padding_right=4
)
sketchybar --default "${default[@]}"

source "$ITEM_DIR/display_change.sh"

items=()
##### Adding Left Items #####
POSITION="left"
source "$ITEM_DIR/aerospace_mode.sh"
source "$ITEM_DIR/aerospace.sh"
source "$ITEM_DIR/front_app.sh"

##### Adding Right Items #####
POSITION="right"
source "$ITEM_DIR/clock.sh"
source "$ITEM_DIR/focus.sh"
source "$ITEM_DIR/volume.sh"
source "$ITEM_DIR/battery.sh"
source "$ITEM_DIR/keyboard.sh"
source "$ITEM_DIR/wifi.sh"

# Additional position (e.g. center) are available, see:
# https://felixkratz.github.io/SketchyBar/config/items#adding-items-to-sketchybar
# More info about the event system can be found here:
# https://felixkratz.github.io/SketchyBar/config/events

sketchybar "${items[@]}"

##### Force all scripts to run the first time (never do this in a script) #####
sketchybar --update
